key: simple
version: 1
slots: []
manualMoves:
    - { from: '*', to: '*' }
backoffMinutes: [10, 60, 360]
workTimeoutMinutes: 120
rules:
    - id: merged
      when:
          all:
              - pr.all_finished_one_merged: {}
              - card.children_finished: {}
      then: { move: { to: '@terminal' } }

    - id: closed-unmerged
      when: { pr.all_closed_unmerged: { minutes: 10 } }
      then: { move: { to: '@backlog' } }
