twig:
    file_name_pattern: '*.twig'
    globals:
        site_review_widget_token: '%env(SITE_REVIEW_WIDGET_TOKEN)%'
    paths:
        '%kernel.project_dir%/templates/Module/Account': 'Account'
        '%kernel.project_dir%/templates/Module/SiteReview': 'SiteReview'
        '%kernel.project_dir%/var/tailwind': 'tailwind'
        '%kernel.project_dir%/assets/styles': 'EmailStyles'

when@test:
    twig:
        strict_variables: true
