<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260725143358 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create feature_flag table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE feature_flag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tags JSONB NOT NULL, options JSONB DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, value JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_83DE64E95E237E06 ON feature_flag (name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE feature_flag');
    }
}
