<?php

declare(strict_types=1);

namespace App\Module\DesignSystem;

/**
 * Every building block of the design system, in one place. A child card adds
 * the entry for its component in the same branch that adds the component.
 */
final readonly class Catalog
{
    /** @return list<ComponentEntry> */
    public function entries(): array
    {
        return [
            new ComponentEntry(
                name: 'Button',
                rootClass: 'lp-btn',
                template: 'components/Ds/Button.html.twig',
                variants: ['primary', 'inverse', 'outline', 'success', 'danger', 'ghost', 'danger-ghost', 'on-card', 'icon', 'compact', 'open'],
                states: ['hover', 'active', 'disabled'],
                enforced: true,
                sizes: ['sm', 'lg'],
                group: 'core',
                summary: 'Any action or link that looks like a button.',
                element: 'button',
            ),
            new ComponentEntry(
                name: 'Input',
                rootClass: 'lp-input',
                template: 'components/Ds/Input.html.twig',
                variants: ['mono'],
                states: ['focus', 'disabled'],
                enforced: true,
                group: 'core',
                summary: 'A one-line text field.',
                element: 'input',
            ),
            new ComponentEntry(
                name: 'Select',
                rootClass: 'lp-select',
                template: 'components/Ds/Select.html.twig',
                variants: [],
                states: ['focus', 'disabled'],
                enforced: true,
                group: 'core',
                summary: 'A drop-down list of options.',
                element: 'select',
            ),
            new ComponentEntry(
                name: 'Textarea',
                rootClass: 'lp-textarea',
                template: 'components/Ds/Textarea.html.twig',
                variants: [],
                states: ['focus', 'disabled'],
                enforced: true,
                group: 'core',
                summary: 'A text field of several lines.',
                element: 'textarea',
            ),
            new ComponentEntry(
                name: 'Label',
                rootClass: 'lp-label',
                template: 'components/Ds/Label.html.twig',
                variants: [],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'The name of a form control.',
                element: 'label',
            ),
            new ComponentEntry(
                name: 'FormField',
                rootClass: 'lp-form-field',
                template: 'components/Ds/FormField.html.twig',
                variants: [],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'A form field with its label, control, hint and errors.',
                element: 'div',
            ),
            new ComponentEntry(
                name: 'FieldErrors',
                rootClass: 'lp-field-errors',
                template: 'components/Ds/FieldErrors.html.twig',
                variants: [],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'The list of errors of a form field.',
                element: 'div',
            ),
            new ComponentEntry(
                name: 'Hint',
                rootClass: 'lp-form-hint',
                template: 'components/Ds/Hint.html.twig',
                variants: [],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'A line of help under a form control.',
                element: 'p',
            ),
            new ComponentEntry(
                name: 'Flash',
                rootClass: 'lp-flash',
                template: 'components/Ds/Flash.html.twig',
                variants: ['success', 'error', 'warning', 'info'],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'A short message about the result of an action.',
                element: 'div',
                dotClass: 'lp-flash__dot',
                contentClass: 'lp-flash__message',
            ),
            new ComponentEntry(
                name: 'EmptyState',
                rootClass: 'lp-empty-state',
                template: 'components/Ds/EmptyState.html.twig',
                variants: [],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'The block that tells a user a list or page has no content yet.',
                element: 'div',
            ),
            new ComponentEntry(
                name: 'Badge',
                rootClass: 'lp-badge',
                template: 'components/Ds/Badge.html.twig',
                variants: ['in-review', 'draft', 'approved', 'changes-requested'],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'A small label for the review status of a document.',
                element: 'span',
            ),
            new ComponentEntry(
                name: 'Tag',
                rootClass: 'lp-tag',
                template: 'components/Ds/Tag.html.twig',
                variants: ['neutral', 'lime', 'purple', 'green', 'amber', 'red', 'teal', 'sky', 'blue', 'indigo', 'pink', 'orange'],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'A small coloured label for a category or a tone.',
                element: 'span',
            ),
            new ComponentEntry(
                name: 'StatusChip',
                rootClass: 'lp-status-chip',
                template: 'components/Ds/StatusChip.html.twig',
                variants: ['pending', 'addressed', 'resolved', 'ok', 'failed', 'neutral'],
                states: ['reason'],
                enforced: true,
                group: 'core',
                summary: 'A chip that names a state, with an optional reason in a tooltip.',
                element: 'span',
                dotClass: 'lp-status-chip__dot',
            ),
            new ComponentEntry(
                name: 'StateMark',
                rootClass: 'lp-state-mark',
                template: 'components/Ds/StateMark.html.twig',
                variants: ['stuck', 'needs-you', 'working', 'waiting'],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'An icon that names what a card needs now, with its reason in an interactive tooltip.',
                element: 'span',
            ),
            new ComponentEntry(
                name: 'StatusBox',
                rootClass: 'lp-status-box',
                template: 'components/Ds/StatusBox.html.twig',
                variants: ['stuck', 'needs-you', 'working', 'waiting'],
                states: [],
                enforced: true,
                group: 'core',
                summary: 'The state of a card with its reason, its facts, what clears it, and the other states that apply.',
                element: 'section',
                dotClass: 'lp-status-box__dot',
            ),
            new ComponentEntry(
                name: 'Dialog',
                rootClass: 'lp-dialog',
                template: 'components/Ds/Dialog.html.twig',
                variants: ['document', 'search'],
                states: ['open'],
                enforced: true,
                group: 'core',
                summary: 'A modal window over the page, opened by the modal controller.',
                element: 'dialog',
            ),
            new ComponentEntry(
                name: 'Tabs',
                rootClass: 'lp-tabs',
                template: 'components/Ds/Tabs.html.twig',
                variants: [],
                states: ['hover', 'selected'],
                enforced: true,
                group: 'core',
                summary: 'A row of tabs that switches between views of one page.',
                element: 'nav',
            ),
            new ComponentEntry(
                name: 'Pagination',
                rootClass: 'lp-pagination',
                template: 'components/Ds/Pagination.html.twig',
                variants: [],
                states: ['current', 'disabled'],
                enforced: true,
                group: 'core',
                summary: 'The previous, next and page-number links of a long list.',
                element: 'nav',
            ),
            new ComponentEntry(
                name: 'Tooltip',
                rootClass: 'lp-tooltip',
                template: 'components/Ds/Tooltip.html.twig',
                variants: ['interactive'],
                states: ['visible'],
                enforced: true,
                group: 'core',
                summary: 'A short label that shows over an element on hover or focus. The interactive variant stays open for a link.',
                element: 'span',
            ),
        ];
    }
}
